### ISSUE TITLE
Truncated data file in GEO

### ISSUE THREAD

**Issue by csoneson** [gtca/crispra_zga#1]
Hi - thanks for making the data and code for this study available! I was interested in looking into the data, and downloaded the `GSE135621_RAW.tar` archive from the GEO record. However, it seems that at least one file (`GSM4023611_Replicate1_2_matrix.mtx.gz`) is truncated: 

```
GSE135621_RAW charlotte$ gunzip -c GSM4023611_Replicate1_2_matrix.mtx.gz | tail
27701 92551 1
27703 92551 1
27710 92551 3
27711 92551 1
27720 92551 1
27723 92551 1
27735 92551 1
27740 92551 1
27746 92551 5
27756GSE135621_RAW charlotte$
```

From what I can see, you are using the `.h5` files in your analysis. Would you be able to confirm the issue with the file above, and update the GEO record (or are the `.h5` files available somewhere)?

Thanks!

**Comment by gtca** [comment]
Hi Charlotte, thank you for reaching out!
It seems like there's a technical issue with this file indeed. We'll look if that can be fixed soon.

The scripts for data loading are indeed using `.h5` files that are also available in the CellRanger's output but for data sharing plain text ones seemed more appropriate, and `sc.read_10x_h5` can be easily swapped to `sc.read_10x_mtx` then.

I hope I'll be able to get back to you soon with good news regarding that one sample!

**Comment by csoneson** [comment]
Thanks!

**Comment by gtca** [comment]
Hello Charlotte, the sample has been fixed on GEO and is available either as [GSM4023611](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM4023611) or as a part of [GSE135621](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE135621). Once again, thanks for reporting the issue!

In case you might find it helpful, since the files shared on GEO are `raw_gene_bc_matrices`, I also uploaded lists of cell barcodes called by Cell Ranger (i.e. from `filtered_gene_bc_matrices`) [here on figshare](https://figshare.com/s/50500c2216d7ba617876) and added a respective note to the `README.md` file in the repository.

**Comment by csoneson** [comment]
Thank you! Much appreciated.
